# Generated by Django 3.2.4 on 2021-08-03 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('blood_sugar', models.IntegerField()),
                ('at_what_time', models.CharField(choices=[('before_breakfast', 'Before Breakfast'), ('after_breakfast', 'After Breakfast'), ('before_lunch', 'Before Lunch'), ('after_lunch', 'After Lunch'), ('before_dinner', 'Before Dinner'), ('after_dinner', 'After Dinner')], max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
