# Generated by Django 3.2.4 on 2021-07-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='diet_preference',
            field=models.CharField(choices=[('V', 'Vegetarian'), ('N', 'Non-Vegetarian')], default='V', max_length=1),
        ),
    ]
